import React, { ReactNode } from 'react';
import '../scss/main.scss';
import { Open_Sans } from 'next/font/google';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';

// Move the metadata export to the top level of the file
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const open_sans = Open_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}