import '../scss/main.scss'
import { Open_Sans } from 'next/font/google'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const open_sans = Open_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
